### ISSUE TITLE
Changelog does not consider the new tag added by npm-version task

### ISSUE THREAD

**Issue by dhinus** [FrancescoCioria/smooth-release#68] opened 2017-02-01 17:11 UTC
It seems that `smooth-release` is not working correctly if called with `smooth-release minor`. The tag is generated with the correct version number, but the Changelog contains `Unreleased` where the version number should be, and the GitHub release contains no title and no description.

This does not happen if I call `smooth-release` with a specific version number, e.g. `smooth-release 0.2.0`.

**Comment by dhinus** [comment] 2017-02-06 16:24
Not sure if it's for the same reason, but I noticed the [changelog for this repo](https://github.com/FrancescoCioria/smooth-release/blob/master/CHANGELOG.md) is also showing `Unreleased` instead of the latest release number (v7.0.0).

**Comment by FrancescoCioria** [comment] 2017-02-06 17:10
> Not sure if it's for the same reason, but I noticed the changelog for this repo is also showing Unreleased instead of the latest release number (v7.0.0).

That's correct: If you close some issues without publishing a new version they end up in the "Unreleased" section. They're the issues already closed and merged on `master` but not yet released on `npm`

I thought you had an `Undefined` section.

If what you had was an `Unreleased` section that's actually ok :)

If you had however released a version than it's indeed a defect and it's probably caused by either:
- GitHub not returning the newly created and pushed `tag` for some reason (cache?)
- `smooth-release`s logic somewhere is not complete :P

**Comment by dhinus** [comment] 2017-02-06 17:42
Yes I had `Unreleased`, I think I wrote `Undefined` somewhere but it was a mistake.

For `smooth-release` though, version 7 does exist, so I think it should appear in the Changelog?

**Comment by dhinus** [comment] 2017-02-06 17:46
Sorry, reading again you say "released **on npm**", that could explain it but it's pretty confusing.

In Contacthub, for example, I now managed to release v0.2.0 and it appears in the [Changelog](https://github.com/contactlab/contacthub-sdk-nodejs/blob/master/CHANGELOG.md), even if it's not been pushed to npm.

**Comment by FrancescoCioria** [comment] 2017-02-06 17:46
> For smooth-release though, version 7 does exist, so I think it should appear in the Changelog?

yes.


Oh, I got it! Stupid me!
After #57 we're generating the changelog **before** adding the tag and pushing it to GitHub!

The `changelog` logic should be improved to handle the case where the tag has not yet been created and is therefore not available through the GitHub API.

**Closed as completed** 2017-02-24 21:28 UTC
Labels: bug
